addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip, testbuild.zip]
    target_paths: 2b36610a-5f65-4d7d-ab3e-737ed03a39d4
after_success: ['./mvnw package dependency:copy-dependencies test jacoco:report coveralls:report']
before_script: [./mvnw install -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
    || true, ./mvnw install -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true]
install: true
jdk: [oraclejdk8]
language: java
script: ./aline-build.sh;./df-build.sh
services: [mongodb, redis]
sudo: false
# Modified by Insights Service at 2016-03-14 18:17:40.261237
