language: java
jdk:
  - oraclejdk8
services:
  - mongodb
  - redis

sudo: false
install: true
before_script:
- mvn install -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true || true
- mvn install -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
script: ./aline-build.sh

addons:
  artifacts:
    target_paths: springboot/$TRAVIS_BUILD_NUMBER
    paths:
      - ./aline-artifacts.zip
   
