language: java
jdk:
  - oraclejdk8
services:
  - mongodb
  - redis

sudo: false
install: true
before_script:
- ./mvnw install -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true || true
- ./mvnw install -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
script: ./aline-build.sh

after_success:
  - ./mvnw package dependency:copy-dependencies test jacoco:report coveralls:report

addons:
  artifacts:
    target_paths: springboot/$TRAVIS_BUILD_NUMBER
    paths:
      - ./aline-artifacts.zip
   
